### PR TITLE
update to latest rust

### PR DESCRIPTION
**Pull request by kstep**

### CODE REVIEW

**Comment by kstep** [comment]
Offtopic: are you going to publish to crates.io? It would be very nice to see your package there.

**Comment by o11c** [comment]
@kstep I haven't seen the point of publishing to crates.io until I don't have to publish a new version number just because there's a new rust nightly.

**Comment by kstep** [comment]
I made the same mistake with my rust-scgi, and now, when I decided to publish it, the name was already busy on crates.io, so I had to rename my crate to simple-cgi. So consider it a friend's advice :)

**Comment by o11c** [comment]
The fact that names are trivially poachable is another reason to avoid crates.io

**Pull request merged**
